{% set name = "bmi-c" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/csdms/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b42aa757fbf11cfda91aef54d74de9c3236452fd8eb13d6803b42a50e5d893d8

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}    # [unix]
    - {{ compiler('cxx') }}  # [win]
    - make  # [unix]

test:
  commands:
    - test -f $PREFIX/include/bmi.h          # [unix]
    - test -f $PREFIX/lib/pkgconfig/bmic.pc  # [unix]
    - if not exist %LIBRARY_INC%\\bmi.h exit 1               # [win]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\bmic.pc exit 1  # [win]

about:
  home: https://bmi.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'C specification for the Basic Model Interface'
  description: |
    C bindings for the CSDMS Basic Model Interface (BMI). This package
    includes a header file with an interface to be implemented by a
    model developer when they add a BMI to their model.
  doc_url: https://bmi.readthedocs.io
  dev_url: https://github.com/csdms/bmi-c

extra:
  recipe-maintainers:
    - mdpiper
    - mcflugen
