travis:
  secure:
    BINSTAR_TOKEN: mG2sEBd+AiNKuDMZ4GemSV+GFfTWxGwQuLxl6gv9T0cW3anJZ4Mxogi5gK6RRDlhNCrTgvMSZJbXXfDBO9azu65X99EvPvhPvtWS/Jj9CyXLPx1TTPTkTzTLfpjO5mwpoLkNZ4aEu7We3GM+F6GP67X758RXA4KIV7G1tnp6rt6SZ/S7gb7gQRw0XD41H512NImnfSjyPoj0kYpSi3F9wxOc6sMF/mGXHtHJqIZo/pIz23tQVcbif6h2EeuRxCU4pjBJIw8XPsu2fthLtJvmhHxIWakralKKplmo/26CyHlFnOo5K9zXuD2w7brGzRuekTxSupV3n7ZdJdjCPgWmzQwa9nzhgP2vQ8WbCOOSrloux4tf4ADl0qBLzgglPFkJxVyXcYzlbbdb2U/JvOvMM5QqDTwSFKasZUkuRXKyB2p2+aciUghW/TzVK6XpI28rW9Xo7h0FO/z0lkDUYSRzSptFCjeg+3ymTuZJ8pG7raoifwGf/Gadc6GgO3c4cQdSX05r9+tWPgzun0DX9djkzyAhwMvqtiijeS4KjyjIEur0tEQfFtecj4QTqqaYxc7zaFv2wxBIFwQzRmFegBVIPrAGJ8OcX6UwRGh1PkcwnHD0DZNKt45AgD062pL2IqZ3i8syke5iURVaAJicS3Pcsdi5BxWgTQuUjqeLQsheOWU=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
